BringMeHome/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from web_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
            url(r'^$', views.index, name='index'),
            url(r'^web_app/', include('web_app.urls')),
            # above maps any URLs starting
            # with web_app/ to be handled by
            # the web_app application
            url(r'^admin/', admin.site.urls),
        ] + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web_app/urls.py
from django.conf.urls import url
from web_app import views
from django.conf.urls import include


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'about/', views.about, name='about'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^register/$',views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^logout/$', views.user_logout, name='invalid'),
    url(r'found_posts/$', views.found_posts, name='found_posts'),
    url(r'lost_posts/$', views.lost_posts, name='lost_posts'),
    url(r'^add_post/$', views.add_post, name='add_post'),
    url(r'^post/(?P<postId>[\w\-]+)/$', views.show_post, name='show_post'),
    url(r'^profile/', views.view_profile, name='view_profile'),
    url(r'^user/(?P<userID>[\w\-]+)/$', views.view_user, name='view_user'),
    url(r'^delete/$', views.user_delete, name='delete'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^auth/', include('social_django.urls', namespace="social")),
]

web_app/models.py
# Create your models here.
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Post(models.Model):
    # postId = models.ForeignKey(Category, on_delete=models.PROTECT)
    postId = models.AutoField(primary_key=True)
    title = models.CharField(max_length=65, default="")
    # date = models.DateTimeField(max_length=50, null=True)
    date = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=2000)
    # image = models.ImageField(upload_to='post_images/')
    image = models.ImageField(upload_to='post_images/', 
        null=True, 
        blank=True)
    status = models.IntegerField(default=False)
    location = models.CharField(max_length=128, default="")
    # found = models.BooleanField(default=True)
    userId = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    # slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.postId)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):  # For Python 2, use __unicode__ too
        return str(self.postId)


class Comment(models.Model):
    commentId = models.AutoField(primary_key=True)
    text = models.CharField(max_length=256)
    date = models.DateTimeField(auto_now_add=True)
    userId = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    postId = models.ForeignKey(Post, related_name='comments', null=True, on_delete=models.CASCADE)


class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # The additional attributes we wish to include.
    phoneNumber = models.IntegerField(default='0')
    location = models.CharField(max_length=250, default="Athens, Greece")
    photo = models.ImageField(upload_to='profile_images/', blank=True)

    def __str__(self):
        return str(self.user)

web_app/forms.py
from django import forms
from django.contrib.auth.models import User
from web_app.models import UserProfile, Post, Comment
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')
        help_texts = {
            'username': None,
            'email': None,
        }


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phoneNumber', 'location', 'photo')


class PostForm(forms.ModelForm):
    CHOICES = [
        ('1', 'Found'),
        ('2', 'Lost'),
    ]

    status = forms.CharField(label='Post Type', widget=forms.Select(choices=CHOICES))
    
    title = forms.CharField(
        max_length=65,
        label='Post Title'
        # widget=forms.Textarea(attrs={'placeholder': 'Title'})
    )

    text = forms.CharField(
        max_length=2000,
        label='Description',
        widget=forms.Textarea(attrs={'placeholder': 'Write your description here...', 'class': 'full-width'})
    )

    location = forms.CharField(
        max_length=250,
        label='Location'
    )

    class Meta:
        model = Post
        fields = ('status', 'title', 'location', 'text', 'image')

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them.
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        # exclude = ('category',)


class CommentForm(forms.ModelForm):

    text = forms.CharField(
        max_length=2000,
        widget=forms.Textarea(attrs={'placeholder': 'Your Message*', 'class': 'full-width'}),
    )

    class Meta:
        model = Comment
        fields = ('text', )

# class EditProfileForm(forms.ModelForm):

#     template_name='/something/else'

#     class Meta:
#         model = UserProfile
#         fields = (
#             'phoneNumber',
#             'location'
#         )

web_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from web_app.forms import UserForm, UserProfileForm, PostForm, CommentForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime
from web_app.models import Post, User, UserProfile
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect
from django.urls import reverse


# Create your views here.


def index(request):
    # Construct a dictionary to pass to the template engine as its context.
    # Note the key boldmessage is the same as {{ boldmessage }} in the template!

    # Return a rendered response to send to the client.
    # We make use of the shortcut function to make our lives easier.
    # Note that the first parameter is the template we wish to use.

    post_list = Post.objects.order_by('-date')[:6]
    context_dict = {'posts': post_list}

    request.session.set_test_cookie()

    # Call the helper function to handle the cookies
    visitor_cookie_handler(request)

    # Obtain our Response object early so we can add cookie information.
    response = render(request, 'web_app/index.html', context_dict)

    # Return response back to the user, updating any cookies that need changed.
    return response


def found_posts(request):
    post_list = Post.objects.order_by('-date').filter(status=1)
    context_dict = {'posts': post_list}

    response = render(request, 'web_app/found_posts.html', context_dict)
    return response


def lost_posts(request):
    post_list = Post.objects.order_by('-date').filter(status=2)
    context_dict = {'posts': post_list}

    response = render(request, 'web_app/lost_posts.html', context_dict)
    return response


def about(request):
    request.session.set_test_cookie()

    # Call the helper function to handle the cookies
    visitor_cookie_handler(request)

    # Obtain our Response object early so we can add cookie information.
    response = render(request, 'web_app/about.html')

    # Return response back to the user, updating any cookies that need changed.
    return response

def contact(request):
    request.session.set_test_cookie()

    # Call the helper function to handle the cookies
    visitor_cookie_handler(request)

    # Obtain our Response object early so we can add cookie information.
    response = render(request, 'web_app/contact.html')

    # Return response back to the user, updating any cookies that need changed.
    return response


def register(request):
    # A boolean value for telling the template
    # whether the registration was successful.
    # Set to False initially. Code changes value to
    # True when registration succeeds.
    registered = False
    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()
            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()
            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves,
            # we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user
            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and
            # put it in the UserProfile model.
            if 'photo' in request.FILES:
                profile.photo = request.FILES['photo']
            # Now we save the UserProfile model instance.
            profile.save()
            # Update our variable to indicate that the template
            # registration was successful.
            registered = True
        else:
            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            print(user_form.errors, profile_form.errors)
    else:
        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
        user_form = UserForm()
        profile_form = UserProfileForm()
        # Render the template depending on the context
    return render(request,
                  'web_app/register.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    # If the request is a HTTP POST, try to pull out the relevant information.
    invalid = False;
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        # We use request.POST.get('<variable>') as opposed
        # to request.POST['<variable>'], because the
        # request.POST.get('<variable>') returns None if the
        # value does not exist, while request.POST['<variable>']
        # will raise a KeyError exception.
        username = request.POST.get('username')
        password = request.POST.get('password')
        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)
        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print("Invalid login details: {0}, {1}".format(username, password))
            invalid = True
            return render(request, 'web_app/login.html', {'invalid': invalid})
            # return HttpResponse("Invalid login details supplied.")

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.

    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'web_app/login.html', {'invalid': invalid})


@login_required
def user_delete(request):
    user = request.user
    user.delete()
    deleted = True

    return render(request,
                  'web_app/accounts/profile.html',
                  {'deleted': deleted})

@login_required
def edit_profile(request):
    updated = False

    if request.method == 'POST':
        if(request.POST['location']):
            location = request.POST['location']
        else:
            location = None
        
        if(request.POST['phoneNumber']):
            phoneNumber = request.POST['phoneNumber']
        else:
            phoneNumber = None

        user = request.user
        user.profile, c = UserProfile.objects.get_or_create(user=user)
        user.profile.location = location
        user.profile.phoneNumber = phoneNumber
        form = UserProfileForm(request.POST, instance=user.profile)
        if form.is_valid():
            form.save()
            updated = True
            args = {'updated': updated}
            # return render(request, 'web_app/accounts/profile.html', args)
            return HttpResponseRedirect(reverse('edit_profile'))
        else:
             updated = False
             args = {'updated': updated}
            #  return render(request, 'web_app/accounts/profile.html', args)
             return HttpResponseRedirect(reverse('edit_profile'))
    else:
        args = {'user': request.user}
        return render(request, 'web_app/accounts/profile.html', args)

@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return HttpResponseRedirect(reverse('index'))


def view_user(request, userID):
    if userID:
        profile = User.objects.get(pk=userID)
    args = {'profile': profile}
    return render(request, 'web_app/accounts/user.html', args)


@login_required
def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'web_app/accounts/profile.html', args)


# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


# Updated the function definition
def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,
                                               'last_visit',
                                               str(datetime.now()))

templates/web_app/accounts/profile.html
{% extends 'web_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
Register
{% endblock %}

{% block body_block %}
<section class="s-extra">
    <div class="row">
        {% if deleted %}
        <strong>Your User account has now been deleted!</strong><br />
        <a href="{% url 'index' %}">Click here to return to the homepage.</a><br />
        {% else %}
        <h1 style="margin-left: 43%; padding-bottom: 20px; color: #fc7070">Profile</h1>

        {% if user == None %}
        <strong>No user provided</strong>
        {% else %}

        <div class="column" style="float:left; width: 70%;">
            <div class="container">
                <!-- {{user.userprofile.id}} -->
                <form id='save' method="post" action="{% url 'edit_profile' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h3>Personal Infomration</h3>
                    <div class="input-w">
                        <label for="id_username"
                            style="max-width: 20%; font-size:20px; display: inline-block;">Username:</label>
                        <input name="username" id="id_username" type="text" value="{{ user }}"
                            style="display: inline-block; max-width: 30%; font-size:20px;" disabled>
                    </div>
                    <div class="input-w">
                        <label for="id_first_name" style="max-width: 20%; font-size:20px; display: inline-block;">First
                            name:</label>
                        <input name="first_name_1" id="id_first_name" type="text" value="{{ user.first_name }}"
                            style="display: inline-block; max-width: 30%; font-size:20px;" disabled>
                        <input name="first_name" id="id_first_name" type="hidden" value="{{ user.first_name }}"
                            style="display: inline-block; max-width: 30%; font-size:20px;">
                    </div>
                    <div class="input-w">
                        <label for="id_last_name" style="max-width: 20%; font-size:20px; display: inline-block;">Last
                            name:</label>
                        <input name="last_name" id="id_last_name" type="text" value="{{ user.last_name }}"
                            style="display: inline-block; max-width: 30%; font-size:20px;" disabled>
                        <input name="last_name" id="id_last_name" type="hidden" value="{{ user.last_name }}"
                            style="display: inline-block; max-width: 30%; font-size:20px;">
                    </div>
                    <div class="input-w">
                        <label for="id_location"
                            style="max-width: 20%; font-size:20px; display: inline-block;">Location/City:</label>
                        <input name="location" size="30" id="id_location" type="text"
                            value="{{ user.userprofile.location }}"
                            style="display: inline-block; max-width: 30%; font-size:20px;">
                    </div>
                    <h3>Contact Details</h3>
                    <div class="input-w">
                        <i class="fa fa-phone" aria-hidden="true"></i>
                        <input name="phoneNumber" id="id_phoneNumber" type="text"
                            value="{{ user.userprofile.phoneNumber }}"
                            style="display: inline-block; max-width: 30%; font-size:20px;">
                    </div>
                    <div class="input-w">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                        <input name="email" id="id_email" type="text" value="{{ user.email }}"
                            style="display: inline-block; max-width: 30%; font-size:20px;" disabled>

                    </div>

                    <!-- <input name="submit" type="submit" value="Register"> -->
                    <input type='button' onclick="JSalert(this.form);"
                        class="btn btn--save btn-wide btn--large full-width" value='Save' />
                        <p>***Only location and phone number can be changed through this form.<br>For further information or requests please contact us.</p>
                </form>


                <form id="deletion" method="post" action="{% url 'delete' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type='button' onclick="JSalert(this.form);"
                        class="btn btn--delete btn-wide btn--large full-width" value='Delete Profile' />
                </form>
            </div>
        </div>
        <div class="column" style="float: right; width: 25%;">
            {% if user.userprofile.photo %}
            <img src="{{ user.userprofile.photo.url }}" style="width: 240px; height: 240px">
            {% endif %}
        </div>
        {% endif %}
        {% endif %}
    </div>
</section>
<script type='text/javascript'>setPage('profile')</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAOwO2A_hmXFVDvjhz5Ygv9m-ZvR1_gYcM&libraries=places&callback=initMap">
    </script>
{% endblock %}

templates/web_app/accounts/user.html
{% extends 'web_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
Register
{% endblock %}

{% block body_block %}
<section class="s-extra">
    <h1 style="margin-left: 43%; padding-bottom: 20px; color: #fc7070">Profile</h1>
    
    {% if profile == None %}
    <strong>No user provided</strong>
    {% else %}
    <div class="row">
        <div class="column" style="float:left; width: 70%;">
            <div class="container">
                    {% csrf_token %}
                    <h3>Personal Infomration</h3>
                    <div class="input-w">
                        <label for="id_username"
                            style="max-width: 20%; font-size:20px; display: inline-block;">Username:</label>
                        <input name="username" id="id_username" type="text" value="{{ profile }}"
                            style="display: inline-block; max-width: 30%; font-size:20px;" disabled>
                    </div>
                    <div class="input-w">
                        <label for="id_first_name" style="max-width: 20%; font-size:20px; display: inline-block;">Last
                            name:</label>
                        <input name="first_name_1" id="id_first_name" type="text" value="{{ profile.first_name }}"
                            style="display: inline-block; max-width: 30%; font-size:20px;" disabled>
                        <input name="first_name" id="id_first_name" type="hidden" value="{{ profile.first_name }}"
                            style="display: inline-block; max-width: 30%; font-size:20px;">
                    </div>
                    <div class="input-w">
                        <label for="id_last_name" style="max-width: 20%; font-size:20px; display: inline-block;">First
                            name:</label>
                        <input name="last_name" id="id_last_name" type="text" value="{{ profile.last_name }}"
                            style="display: inline-block; max-width: 30%; font-size:20px;" disabled>
                        <input name="last_name" id="id_last_name" type="hidden" value="{{ profile.last_name }}"
                            style="display: inline-block; max-width: 30%; font-size:20px;">
                    </div>
                    <div class="input-w">
                        <label for="id_location"
                            style="max-width: 20%; font-size:20px; display: inline-block;">Location/City:</label>
                        <input name="location" size="30" id="id_location" type="text"
                            value="{{ profile.userprofile.location }}"
                            style="display: inline-block; max-width: 30%; font-size:20px;" disabled>
                    </div>
                    <h3>Contact Details</h3>
                    <div class="input-w">
                            <i class="fa fa-phone" aria-hidden="true"></i>    
                            <input name="phoneNumber" id="id_phoneNumber" type="text"
                                value="{{ profile.userprofile.phoneNumber }}"
                                style="display: inline-block; max-width: 30%; font-size:20px;" disabled>
                    </div>
                    <div class="input-w">
                            <i class="fa fa-envelope" aria-hidden="true"></i>    
                            <input name="email" id="id_email" type="text"
                                value="{{ profile.email }}"
                                style="display: inline-block; max-width: 30%; font-size:20px;" disabled>
                                
                    </div>
            </div>
        </div>
        <div class="column" style="float: right; width: 25%;">
            {% if profile.userprofile.photo %}
            <img src="{{ profile.userprofile.photo.url }}" style="width: 240px; height: 240px">
            {% endif %}
        </div>
    {% endif %}
</section>

{% endblock %}